# Generated by Django 4.1 on 2022-11-28 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="userInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("bio", models.TextField()),
                (
                    "joined_date",
                    models.DateField(
                        default=datetime.datetime(2022, 11, 28, 16, 34, 12, 164759)
                    ),
                ),
                ("email_id", models.EmailField(max_length=254)),
                ("is_login", models.BooleanField(default=False)),
            ],
        ),
    ]
