# Generated by Django 4.1 on 2022-11-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("all_music", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="playlist", name="song",),
        migrations.AddField(
            model_name="playlist",
            name="song",
            field=models.ManyToManyField(to="all_music.song"),
        ),
    ]
