# Generated by Django 4.1 on 2022-11-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("all_music", "0002_remove_playlist_song_playlist_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
