# Generated by Django 4.1 on 2022-11-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("all_music", "0003_alter_playlist_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
